const envs = {
  CURRENCY_SYMBOL: process.env.NEXT_PUBLIC_CURRENCY_SYMBOL,
  MINIMUM_ORDER_VALUE_FOR_FREE_SHIPPING:
    process.env.NEXT_PUBLIC_MINIMUM_ORDER_VALUE_FOR_FREE_SHIPPING,
  SHIPPING_CHARGE: process.env.NEXT_PUBLIC_SHIPPING_CHARGE,
  ADMIN_API_BASE_URL: process.env.NEXT_PUBLIC_ADMIN_API_BASE_URL,
  CALORIE_PRICE: process.env.NEXT_PUBLIC_CALORIE_PRICE as unknown as number,
};
export default envs;
